<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete post';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($post->title); ?>' by
     '<?php echo $this->escapeHtml($post->body); ?>'?
 </p>
 <?php
 $url = $this->url('api', array(
     'action' => 'delete',
     'id'     => $post->postId,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $post->postId; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>